import type { Metadata } from "next";
import {
    Bungee_Shade,
    Geist,
    Geist_Mono,
    Georama, Monoton,
    Orbitron, Rampart_One,
    Rubik_Doodle_Shadow,
    Share_Tech,
    TASA_Orbiter
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const georama = Georama({
  variable: "--font-georama",
  subsets: ["latin"],
});
const orbitron = TASA_Orbiter({
    variable: "--font-orbit",
    weight: "400"
})
const logoFont = Rampart_One({
    variable: "--font-logo",
    weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${georama.variable} ${orbitron.variable} ${logoFont.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
